---
- name: Deploy to Minikube
  hosts: servers
  connection: local

  tasks:
    - name: Apply Deployment
      command: kubectl apply -f k8s/deployment.yaml

    - name: Apply Service
      command: kubectl apply -f k8s/service.yaml
